name: Ares
url: https://github.com/fi3ework/hexo-theme-ares

menu:
  Home: /
  Archives: /archives
  About: /about
  RSS: /atom.xml

favicon: /favicon.ico
logo:

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

comment:
  livere_uid: MTAyMC8yODQyOS81MDAw

# Copyright Infomation
copyright:
  since:
  name:
  url:
